---
# Based on https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml
# Based on https://github.com/do-community/ansible-playbooks

php_version: "7.2"

php_packages: [ 'php', 'php-fpm', 'php-mysql', 'php7.2-cli' ]
php_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
php_install_recommends: true

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: false


# TBD: 
#   *  any and all caching
#   *  php.ini managed settings
#   *  php error configuration
#   *  php from source