---

## Dependencies
- name: Add repository for PHP 7.
  apt_repository: repo='ppa:ondrej/php'

- name: Ensure php packages are installed
  apt: 
    pkg: "{{ php_packages }}"
    update_cache: true 
    state: "{{ php_packages_state }}"
  become: true

## Install

## Configure
