---

- name: Personalize by customizing user prompt, hopefully
  become_user: vagrant
  lineinfile:
    dest: ~/.bashrc    
    line: 'PS1="\e[0;30;47m\u@\h:\e[0m \e[1;31;40m \w \e[0m \e[1;32;40m\$ \e[0m"'
    