---

# NODE.JS

- name: Add Nodesource apt key.
  become: True
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  become: True
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_ver }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_ver }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  become: True
  apt:
    update_cache: yes
  when: node_repo.changed

- name: Install nodejs
  become: True
  apt: 
    name: "nodejs={{ nodejs_ver|regex_replace('x', '') }}*"
    state: present
