---
db_packages: [ 'mysql-server', 'python3-pymysql' ]
db_packages_state: present

db_hostname: "{{ v_hostname }}"
db_ip: "{{ v_ip_address }}"

mysql_root_password: "cola"
#http_host: "your_domain"
#http_conf: "your_domain.conf"
#http_port: "80"
