---
# This playbook deploys the whole application stack for
# developing and deploying RoR CRUD apps

- hosts: all
  connection: local

  vars:
    vm_env: dev

  roles:
    - osPackages
#    - db
    - php
    - personalize